### ISSUE TITLE
Help needed with Docker VPN

### ISSUE THREAD

**Issue by gurabli** [fryfrog/ubuntu-qbittorrentvpn#1]
Hi,
I'm contacting you here as I literary spent the last 24 hours to make my config work, but nada. 
The thing is, I manages somehow to configure once on VPS, then I recreated the image, and since then, I can't reproduce.
I was using the DelugeVPN container with Privoxy, and wanted to use the Oscam container with http proxy over DelugeVPN. It just doesn't work. Could you please help me out?

Maybe if you can give me a contact (email) and we could figure something out.

Thanks!

**Comment by Friday13th87** [comment]
i dont think that you can get help like this.
it is absolutely not understandable what your goals are and where the problem is. if you are not even able to write something more what you did, what you like to have etc. why should someone give you a contact address for personal support?
if its on the www then it could be helpful for other people at least...
